### ISSUE TITLE
Player names not visible (only for MTF)

### ISSUE THREAD

**Issue by LaFesta1749** [VersLugia/PlayerInfo#1]
Player names in-game are **not** visible at all.
![image](https://user-images.githubusercontent.com/1494298/219001068-aa225942-b867-432d-bbeb-0ce55e4027c7.png)

![image](https://user-images.githubusercontent.com/1494298/219001178-6c45f554-de37-4894-a5b5-2cb53782128e.png)

Can we get a fix, please?

**Comment by VersLugia** [comment]
Exiled or nw-api?

**Comment by LaFesta1749** [comment]
Exiled Version 6.0.0-beta.26

**Comment by VersLugia** [comment]
I will fix it soon.

**Comment by LaFesta1749** [comment]
Thank you

**Comment by VersLugia** [comment]
Try setting `enable_power_status` to `false` and write what then

**Comment by LaFesta1749** [comment]
I have tried that too. Same result = no names shown at all. Just blank

**Comment by VersLugia** [comment]
[PlayerInfo.zip](https://github.com/VersLugia/PlayerInfo/files/10744552/PlayerInfo.zip)
Try this

**Comment by LaFesta1749** [comment]
It's the same: No name at all.
![image](https://user-images.githubusercontent.com/1494298/219418157-942fda21-40c7-4953-8e27-12ca9f511e39.png)
![image](https://user-images.githubusercontent.com/1494298/219418170-f5466858-cc87-4a70-8225-164415d36b65.png)

**Comment by LaFesta1749** [comment]
> [PlayerInfo.zip](https://github.com/VersLugia/PlayerInfo/files/10744552/PlayerInfo.zip) Try this

Okay, so... I removed the {nick} that's after the "Prisoner" part and it works but is it possible somehow to add the nick afterall ?

![image](https://user-images.githubusercontent.com/1494298/219420234-7f654fed-6db3-47ab-b176-00bbf524facd.png)

**Comment by VersLugia** [comment]
[PlayerInfo.zip](https://github.com/VersLugia/PlayerInfo/files/10757893/PlayerInfo.zip)
Try this, it should be ok now

**Comment by LaFesta1749** [comment]
> [PlayerInfo.zip](https://github.com/VersLugia/PlayerInfo/files/10757893/PlayerInfo.zip) Try this, it should be ok now

Works perfectly. Thank you so much! ♥

**Comment by VersLugia** [comment]
Thanks for the report, I'll make a new release.
